version: "3"

services:
  app:
    build:
      context: ../../
      dockerfile: ./ops-tools/docker/images/app/Dockerfile
    volumes:
      - ../../:/app
    networks:
      - docker-practice-net
    ports:
      - "8888:8080"
    depends_on:
      - postgres
      - redis

  postgres:
    image: "postgres:14.1-alpine"
    restart: always
    networks:
      - docker-practice-net
    ports:
      - "5432:5432"
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
      - ../../data/dump:/db-dump
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: school
      POSTGRES_DB: school

  redis:
    image: "redis:6.2.6-alpine"
    restart: always
    networks:
      - docker-practice-net
    ports:
      - "6379:6379"

networks:
  docker-practice-net:
    driver: bridge

